### ISSUE TITLE
Profile and ProfileWrapper

### ISSUE THREAD

**Issue by saintplay** [anindya-dhruba/laravel-vue-spa#1]
Hi!, new Vue developer here!
there is a reason to have `Profile.vue` and `ProfileWrapper.vue` in two separate folders!?
kinda irrelevant question, but I think these two could be perfectly in the same directory

**Comment by saintplay** [comment]
I ended with this structure:
![image](https://user-images.githubusercontent.com/9372893/28695734-a7e68120-72f6-11e7-946f-2bd9078168fb.png)

**Comment by anindya-dhruba** [comment]
I separated `Profile.vue` in a directory because there can be more components related to profile in future. I did not place `ProfileWrapper.vue` in that directory because `ProfileWrapper.vue` is just a container where the children can be `Profile.vue` or `EditProfile.vue` or `EditPassword.vue`. 

At the same time, I was not trying to pollute the `components` directory by placing `ProfileWrapper.vue` here. 

So, I made a directory `profile-wrapper` and put it there.

I like the directory structure you made and like to go with that structure. I will try to do that in next update. Waiting for the official release of Laravel 5.5
