### ISSUE TITLE
Name and Email setters

### ISSUE THREAD

**Issue by saintplay** [anindya-dhruba/laravel-vue-spa#2]
Hello again,

I'm wondering why creating a mutation and setter for each email and name is good practice?
There is any reason for changing the name and email in the vuex state, before updating them through the api?

![image](https://user-images.githubusercontent.com/9372893/28882624-5f67cb1e-7771-11e7-8ef3-16d1eb433af0.png)

Sorry again for open an issue with this kind of question

**I'm talking about these lines:**
https://github.com/anindya-dhruba/laravel-vue-spa/blob/master/resources/assets/js/components/edit-profile/EditProfileForm.vue#L40-L60

https://github.com/anindya-dhruba/laravel-vue-spa/blob/master/resources/assets/js/store/modules/auth-user.js#L11-L16

PD: I'm kinda a new Vue developer!

**Comment by anindya-dhruba** [comment]
Hi again, 
Sorry for the late reply.

> I'm wondering why creating a mutation and setter for each email and name is good practice?

There is no need to create mutation and setter for each field of a form. If would really smell bad if you have 10 fields in a form and for each field you have mutation and setter. What is good is create a mutation that will take two params as argument, one is the state what is going to change and the new value of this state. Like: `e.target.name` and `e.target.value`

I used this pattern when I was developing apps with react and redux, it looked useful and clean to me.

> There is any reason for changing the name and email in the vuex state, before updating them through the api?

As the values we are displaying in input field comes from vuex, if you don't change the vuex store on change on input, no matter what you type in the input, it won't change, because store is not getting changed. So, this is what we have to do to make it work. 
Another way can be copy the vuex store that you are going to display in form field as local variable (`data`) in that component and display that in input field. 

This post might help you answering both of your question: https://ypereirareis.github.io/blog/2017/04/25/vuejs-two-way-data-binding-state-management-vuex-strict-mode/

The truth is when I made this boilerplate I was also learning vue and vuex. 😄 So, that time what made sense to me, I did it, but now I can determine what is wrong in it. I am still waiting for the official release of Laravel 5.5. It should be released anytime.

Thanks.

**Comment by saintplay** [comment]
I checked the article,
so I think the approach you give to us make sense if two way binding data is required.

I also want to point out this API Setup as a good practice
https://metricloop.com/blog/how-to-make-api-calls-with-vuex
*(Check The API Setup section)*

And this Vuex's module structure
https://metricloop.com/blog/how-to-set-up-modules-in-vuex 
Separation between actions and mutations matters in larger projects, I guess
