### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by MathiasVie** [anindya-dhruba/laravel-vue-spa#6]
Hi!

thanks for the boilerplate. unfortuneately I don't get CORS working ("Failed to load http://localhost/api/authenticate: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."). I have tried to use https://github.com/barryvdh/laravel-cors without success so far. What would be the best way to enable CORS? thanks, kind regards

**Comment by anindya-dhruba** [comment]
Hi,
Thanks for using this boilerplate.

**Did you set `APP_URL` in your `.env` file?**

Here is the `.env.example` file as an example: https://github.com/anindya-dhruba/laravel-vue-spa/blob/master/.env.example#L5

For example: If your app is running at `http://localhost/myapp`,  set `http://localhost/myapp` as `APP_URL` in your `.env` file. Follow same instruction if you are using valet or homestead.

And don't forget to restart the server after changing the `.env`.

Please close the issue if it solves the CORS problem. Otherwise, let me know.

Thanks again.

**Comment by MathiasVie** [comment]
perfect! that was the problem! thanks!

**Comment by dimer22zhc** [comment]
For me it doesn't work guys APP_URL= http://127.0.0.1

**Comment by dimer22zhc** [comment]
`Access to XMLHttpRequest at 'http://localhost/api/authenticate' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

```
app.js:2640 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at app.js:2640
```

**Comment by Nox04** [comment]
> For me it doesn't work guys APP_URL= http://127.0.0.1

Set your APP_URL to http://localhost and try again.
