### ISSUE TITLE
Seeding a new user

### ISSUE THREAD

**Issue by isnipepixels** [anindya-dhruba/laravel-vue-spa#8]
```
c:\xampp\htdocs>php artisan migrate --seed
Migration table created successfully.

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQ
  L: alter table `users` add unique `users_email_unique`(`email`))


In Connection.php line 458:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

**Comment by anindya-dhruba** [comment]
Hello @isnipepixels,
I don't think it's a problem of the repo. Laravel uses `utf8mb4` as default database character set from version 5.4. These links might help you to know more and fix the issue:

https://github.com/laravel/framework/issues/17508
https://laravel-news.com/laravel-5-4-key-too-long-error

Please, close the issue if you can resolve this. Otherwise, let me know.

Thanks.

**Comment by isnipepixels** [comment]
Got you, just forgot I was using a old version of mysql.
